### ISSUE TITLE
Installation stats per major version

### ISSUE THREAD

**Issue by stof** [composer/packagist#1006]
Current, the installation stats are providing a total number, and a number per release (with evolution charts for both of them).

It would be great to have a similar stats per major version (allowing to answer the question "is Twig 1.x used more or less often than Twig 2.x ?" for instance, which is exactly my current use case). Comparing only the latest patch release of each branch is not enough (most used versions of Twig are not actually the latest patch releases right now, due to being recent)

**Comment by stof** [comment]
even better would be to allow drawing the different major versions on the same chart to compare them...

**Comment by nicekiwi** [comment]
Are stats collected in the DB for this?

**Comment by stof** [comment]
Well, I'm quite sure that the current code does not collect such stats in Redis. But we could do it, as the request reports the version (which is used today for exact version graphs), and so we could create an aggregate key per major versions too.

**Comment by Seldaek** [comment]
Stats are in the DB yes, should be easy enough to do a grouped query merging all versions by their major version I think.

**Comment by acornforth** [comment]
I just arrived to this page to request/suggest a very similar thing.
For any given composer package, I would like to see, in the version history for the package (bottom right of page on desktop site, where the warning triangle appears for versions with known security issues) the number of downloads for that version. (another nice to have would be the ability to toggle the view between Total downloads, (since forever) and downloads in the last month/6months etc.

**Comment by Seldaek** [comment]
https://packagist.org/packages/twig/twig/stats 🎉

**Comment by stof** [comment]
@Seldaek @glaubinix thanks a lot for that. :tada:
