### ISSUE TITLE
Packagist not compatible with GeTea

### ISSUE THREAD

**Issue by KarelWintersky** [composer/packagist#1009]
```
Uncaught Exception: [RuntimeException] Failed to execute git clone --mirror 'https://git.wintersky.me/SteamBoat/Test.git' '/home/composer/.composer/cache/vcs/https---git.wintersky.me-SteamBoat-Test.git/' Cloning into bare repository '/home/composer/.composer/cache/vcs/https---git.wintersky.me-SteamBoat-Test.git'... fatal: could not read Username for 'https://git.wintersky.me': No such device or address 
```
after importing repo

**Comment by stof** [comment]
what is this GeTea you are talking about ?

**Comment by KarelWintersky** [comment]
https://gitea.io/en-us/

**Comment by alcohol** [comment]
Packagist only supports public repositories as source.

**Comment by S1SYPHOS** [comment]
When using a public repository on a Gitea instance, it includes `.git` directory inside the installed package - which obviously isn't desirable. This happens regardless of `--prefer-dist` etc so I opened an issue over at [their repository](https://github.com/go-gitea/gitea/issues/19929) addressing the issue.

**Comment by stof** [comment]
Well, there is no composer driver for gitea yet. So composer is not able to know that gitea provides archives for specific commits in the repository (and I don't even know whether gitea has such feature). As such, there is no dist to use and composer will then install from source (that's why the option is named `prefer-dist` and not `use-dist`, as there is no guarantee that a dist will always be used due to not having dists at all).
The support for generic git servers only has source install (by doing a git clone).

**Comment by S1SYPHOS** [comment]
@stof Thanks for letting me know - would there be a way to specify zip file in `composer.json`? Either as URL or inside the repository?

**Comment by Seldaek** [comment]
You can declare it as dist:{url:..., type:zip} in the json (with quotes, sorry on my phone).

Or you can publish things on github or gitlab and make it easier for you to publish and for people to contribute too, but up to you :)

**Comment by S1SYPHOS** [comment]
Yeah, I added a push mirror to GitHub and published its link to Packagist, problem solved for now .. 🦊
