### ISSUE TITLE
Installation stats per PHP versions

### ISSUE THREAD

**Issue by stof** [composer/packagist#1054]
As a package maintainer, I would like to know which PHP versions are used when installing my package, to be able to take better decisions about increasing the min PHP version of my package (if I see that most of my userbase is installing the package on PHP 7.1, dropping support for PHP 7.1 might not be the best choice for instance).
Given that Packagist already collects download stats, and that Composer reports the PHP version in its user-agent, this is a feature that could be provided AFAICT.

**Comment by stof** [comment]
Note that this is not the same request than #482 (although there is some common points), as I'm not interested into seeing the overall stats here, but the per-package stats.

**Comment by Seldaek** [comment]
This is finally available :) See https://blog.packagist.com/sunsetting-the-php-version-stats-blog-series/ for details and sample links.

**Comment by boesing** [comment]
Nice! @Seldaek do you have some more insights on this? Are there GHA/Travis installations included? Is there a way to tell composer to not add an installation to the statistics.

e.g. as a library maintainer, I'd prefer not having my CI installations count into statistics as that may blur the actual result.

But anyways, thats already an amazing feature tho!

**Comment by Seldaek** [comment]
If you really wish to suppress your own installs you can disable this in the config https://getcomposer.org/doc/06-config.md#notify-on-install - that's where we do the tracking. However I would **strongly advise against doing this**.

CI usage is included, because in my experience (I have had the data separated for a while in another system) it does not really matter. It moves the needle a tiny bit sometimes, but it's just not worth filtering IMO.

You also have to consider though that if you disable stats you disable it for your own installs but it also means you don't get counted in the stats of the packages you depend on. So imagine your CI runs on 7.2 - 7.4, you probably want your dependencies to know about this so that they can see people rely on 7.2 - 7.4. Same for real world users, if they build their projects in CI only and then ship archives/containers to prod, you do want those "CI" installs to count, otherwise this usage disappears entirely.

Therefore I find it better to just collect it all and in aggregate it shows a picture that is more or less reality. Of course some people will do more installs than others, and that can skew the stats a little too. Some will be CI, some will be dogs. We can't give you 100% reliable data without forcing user accounts and even then you'd get account sharing, and are servers people? Should you create one account per project? It's an endless debate (which I have decided to ignore a long time ago:).

**Comment by boesing** [comment]
I see, thanks for the insights here. Thats really helpful.
