### ISSUE TITLE
Not detecting new versions of my package

### ISSUE THREAD

**Issue by russell-kitchen** [composer/packagist#1057]
Have added in the necessary webhook, and it picked up the first two versions, but its not picking up any of the other subsequent versions:
https://packagist.org/packages/russell-kitchen/unique-id
https://github.com/russell-kitchen/unique-id/releases

Have tried a suggested solution of adding v to the tags, but nada. Also tried logging in and out.

Any help would be greatly appreciated

**Comment by glaubinix** [comment]
The reason why new versions are not picked up is that you have a version defined in your composer.json (https://github.com/russell-kitchen/unique-id/blob/master/composer.json#L5) which should be omitted see https://getcomposer.org/doc/04-schema.md#version

In your case this results in every version which is not 1.0.0.0 to be skipped because of it:
`Skipped tag v1.1.2, tag (1.1.2.0) does not match version (1.0.0.0) in composer.json`

Whether you add a v to the tag or not will not make a difference.
