### ISSUE TITLE
Dependent packages in JSON

### ISSUE THREAD

**Issue by alexeyshockov** [composer/packagist#1059]
Currently [the list of dependent packages is accessible only in HTML](https://github.com/composer/packagist/blob/cbcdbd9197782ae315496864942defb7b73c27cc/src/Packagist/WebBundle/Controller/PackageController.php#L1002-L1009). IMO it makes sense to allow JSON output in this action as it's already done in other places.

Although #728 will solve all my need, it seems not so easy as just adding JSON output to the existing action.

If you think that this feature is worth implementing, I can prepare a PR.

**Comment by Seldaek** [comment]
Fixed by https://github.com/composer/packagist/commit/6c1127b2e3e0c636ecb9878a0faaba0f696059e2 

See e.g. https://packagist.org/packages/monolog/monolog/dependents?order_by=downloads 
I also added a JSON version for API consumption https://packagist.org/packages/monolog/monolog/dependents.json?order_by=downloads

**Comment by alexeyshockov** [comment]
Thanks a lot!
