### ISSUE TITLE
Package won't update, even after manual update

### ISSUE THREAD

**Issue by khalwat** [composer/packagist#1072]
I have this package:

https://packagist.org/packages/nystudio107/craft

Which has been happily auto-updating for some time. But suddenly, it's no longer auto-updating, even though two new versions have been tagged & released:

https://github.com/nystudio107/craft/releases

Even manually clicking on **Update** on packagist.org seems to have no effect, though it does claim to have updated it.

Any guidance would be wonderful.

**Comment by Seldaek** [comment]
The reason is you have a hardcoded version in composer.json which you forgot to update.

Removing the version property would be easier so you don't need to keep updating it.

Reading composer.json of craftcms/craft (2.2.3)
Skipped tag 2.2.3, tag (2.2.3.0) does not match version (2.2.1.0) in composer.json
Reading composer.json of craftcms/craft (2.2.2)
Skipped tag 2.2.2, tag (2.2.2.0) does not match version (2.2.1.0) in composer.json

**Comment by khalwat** [comment]
Oh god, so sorry to bother you @Seldaek -- thank you.
