### ISSUE TITLE
Package updated on website, but not via API/composer

### ISSUE THREAD

**Issue by weierophinney** [composer/packagist#1080]
Hi!

I discovered we'd not issued some of the 2.4 series of tags for the zendframework/zend-xmlrpc package, which we marked as abandoned on Packagist in early January.

I issued and pushed those tags today (as they affect some migrations to Laminas), and then hit the "Update" link on Packagist to ensure they were pulled in. The website now shows them (2.4.3 - 2.4.13).

However, the API does not report them (https://packagist.org/packages/zendframework/zend-xmlrpc.json), and Composer fails to find the new versions, even after a clear-cache operation, and a couple of hours time. (Both report 2.4.0 - 2.4.2, then jump to 2.5.0, as they did prior to issuing the new tags.)

Is this an issue because the package is marked abandoned? Can I get some assistance resolving this, please?

**Comment by stof** [comment]
The API has a long cache header, due to the cost of computing this info. So this might explain it

Regarding composer, there is a slight delay between the time the Packagist DB is updated and the time the composer repository reflects the change (there is a cron updating the dumped metadata). When trying now, `composer show -a zendframework/zend-xmlrpc` is showing me these versions.

**Comment by weierophinney** [comment]
Yep - I'm showing them now, thanks!

**Comment by stof** [comment]
Note that @Seldaek said in some comment (I don't remember in which issue exactly) that the delay in metadata dumping might disappear once Packagist drops support for Composer 1.x, as the new repository format supported by Composer 2 is meant to allow re-dumping metadata for each package separately. But we are not there yet.
