### ISSUE TITLE
Package download statistics

### ISSUE THREAD

**Issue by Nyholm** [composer/packagist#1081]
I've been thinking a bit about this. Im not super happy with the download statistics. The UI is excellent and I really like it but the data itself could get some improvements. 

### The dream

I would like the download statistics to give an indication of how many people/applications is using a package.

### The problem

The number does not say much at the moment because too many factors are involved. This is an example of two competing packages and both have over 1M downloads. 

![EWhsqP2WoAUvdQn](https://user-images.githubusercontent.com/1275206/81198729-1bbcb200-8fc2-11ea-8fde-427b256c7ebd.jpeg)
![EWhsqQvXgAAwWjG](https://user-images.githubusercontent.com/1275206/81198737-1ceddf00-8fc2-11ea-8f3e-48c12391dfc6.jpeg)

It is clear that CI plays a big role here. 

### Possible solutions

There are a few things I would like to do: 

#### 1. Remove CI downloads. 

Could we add some CI detection logic in composer so it sends an additional parameter to the packages servers if it was running on CI?
Maybe we could also see if the request comes from a large CI  provider like Github, travis, gitlab, bitbucket etc etc. 

Packagist can then save "normal downloads" and "CI downloads".

#### 2. Separate "require", "update" and "install".

I would be interested to see how many new users/applications that are using a package. 

It is also interesting to see how many user that keep using the package, ie running "composer update" and downloading new versions. 

Finally, the count for "install" would be interesting to see for old stable packages that never updates. It would be a secondary indicator of how many users a package have. 

---------

I understand that this may require some tweaks on composer quite some changes on packagist too. I dont thing everything need to be done at once and I also think that all these new numbers I which for could be shown in a "smart" way. Ie, adding them to existing graphs is maybe not ideal. 

I believe that this is something that would give a more fair and more helpful download statistics. Is this something that the project would consider?

**Comment by Seldaek** [comment]
About your two graphs, please mind the fact that depending on the period shown, the data points will represent days or weeks or months, it looks to me like the bottom one is showing daily points while the top one is aggregating per week and has thus less fluctuation due to weekends. So "it is clear CI plays a big role" is nonsense IMO. People work during the week, so stuff happens, they install packages more, but also CIs work more as a consequence. 

1. Nope. It's been discussed a hundred times. This is not gonna happen. Removing CIs would just downscale everything by a bit but it doesn't actually change the relative numbers package A and B will have to each other.

2. This is complicated to achieve, inside Composer it's very hard to distinguish a newly installed/added package (as in require) vs a random package install. The update case is easier to distinguish but also kinda meaningless IMO depending on use case. The frequency of releases a given project has also has an impact on the amount of updates for example.

Overall it seems like a lot of effort to trade an imperfect number for another imperfect number. The bottom line here IMO is that these are just an indication of usage. If something is used more it will have an overall higher number. The exact number is meaningless, and comparing e-penises between packages is kinda a pointless exercise. 

You just have to embrace the fact that you can't possibly know how many users you have.. It's frustrating yes but it's just impossible. Even adding a unique tracking id on every computer would be imperfect, given VMs and docker and build machines and prod servers and whatever the machine ids wouldn't match developers/people.

**Comment by Nyholm** [comment]
Yes, you are correct one of the graphs showed daily stats. My bad. 

1. I am not confident that you are correct that it would just downscale everything. But Im sure more arguments have been discussed before. I'll search around. 

2. Fair, if it is too complex and the win is too small then there is no point. 

Yes, I think you are correct. I am measuring "e-penises". =) 
The download count is a number that is being used to "score" a package. If one has successfully built a perfect SOLID and feature complete package, then its "score" will be worse compared to the package releasing a patch release every day. 

I'll open a new issue when I've found an algorithm for a new "package score" number. 
Thank you for the reply.
