### ISSUE TITLE
version 00.00.2 != 0.0.2 in packagist, but composer seems to treat them the same

### ISSUE THREAD

**Issue by steve-thousand** [composer/packagist#1106]
I am working on a project that is trying to explore the rules for what kind of versions that packagist allows, and we had the wild idea to test leading zeros. I tested adding a tag of `00.00.2` and found that packagist would ingest that and represent it as `00.00.2`. Next I tested adding a tag of `0.0.2` and found that it was also ingested by packagist, as `0.0.2`. However attempting to add the dependency to my project as version `00.00.2`, I am unable to resolve `00.00.2` and instead composer finds `0.0.2`. I also tried the fully qualified normalized version of `00.00.2.0` and it still resolves as `0.0.2`

It seems like packagist considers these two versions to be different, but composer's install logic disagrees.

See the test package for examples https://packagist.org/packages/steve-thousand/composer-test

**Comment by steve-thousand** [comment]
Update on this: 

It looks like Composer's own semver library has code suggesting a legacy format existed which is no-longer documented that supported specifying the version as a date, and the regex for that detection might explain why it is that leading zeros in `00.00.2` are supported https://github.com/composer/semver/blob/master/src/VersionParser.php#L140

But it seems there is still a bug where I cannot specify that date version as the chosen dependency. Perhaps Composer has mentioned somewhere that because they have deprecated that format that they will no-longer be supporting it in the case of constraints and normalized version comparisons?

**Comment by Seldaek** [comment]
The date format stuff is indeed supported and used by some projects, but we don't document it because it's not really bringing anything vs semver IMO and is not necessarily well supported.

What happens is 00.00.2 and 0.0.2 both resolve to `00.00.2.0` and `0.0.2.0` respectively in their normalized form, which is why packagist allows storing both versions independently. This does look like a bug though, it probably shouldn't allow multiple leading zeros.

Because what then happens is `version_compare('00.00.2.0', '0.0.2.0', '==')` is true, so when you request 0.0.2, or 00.00.2, that doesn't matter, both versions match, and it ends up picking whichever sorts higher for other reasons. You can't pick exactly one or the other.

So yeah most likely we should fix the leading zero issue in semver, and then it would disallow storing this in packagist in the first place.

**Comment by Seldaek** [comment]
Looking at this some more, while the fix would be very easy to do, it looks like it will affect quite a few packages using versions like `1.02` or `20.07.13` or `v0.200203.082506`. While everything should keep working fine, I am not sure I want to risk this change. There is basically no benefit to cleaning this up, it doesn't cause issues in reality and sure it's a minor inconsistency but I'd say it's fine to keep as is.

@naderman if you have a different opinion do tell, but otherwise I'd tend to just close this as won't-fix.

**Comment by naderman** [comment]
@Seldaek Agree that this hasn't come up as a real life issue so far, but would probably still add a note to semver docs or so, so one can at least find this if it is an issue?

**Comment by Seldaek** [comment]
Yeah we could add tests too so it's explicitly covered.
