### ISSUE TITLE
Version tagged with v prefix missing the prefix and patch release missing

### ISSUE THREAD

**Issue by crynobone** [composer/packagist#1149]
I experienced an odd behaviour with one of repository:

Git: https://github.com/orchestral/canvas
Packagist: https://packagist.org/packages/orchestra/canvas

I tagged `v4.6.0`, `v5.5.0` and  `v6.1.0` on GitHub but Packagist seem to insist on using `4.6.0`, `5.5.0` and `6.1.0`. Tried removing the tags on Packagist and GitHub and sync everything but the problem still persist. At first I ignored the issue since it still technically resolved the expected version. However last week I released `v6.1.1` on GitHub but it was never synced to Packagist even after trying to do so manually.

**Comment by stof** [comment]
the issue is that your composer.json specify an explicit `version` field.

As [documented](https://getcomposer.org/doc/04-schema.md#version), this fields is useless in VCS repository and only has drawbacks. Versions are automatically inferred from the VCS tags, and a tag which has different versions in the composer.json and the tag name will be considered invalid and skipped (this is what happened to 6.1.1).

Btw, not having the v is probably related to that explicit version too, because the explicit version does not have it.

**Comment by crynobone** [comment]
Ahh, totally didn't expect that. Thank you @stof
