### ISSUE TITLE
Spurious error message on package submission.

### ISSUE THREAD

**Issue by Danack** [composer/packagist#1178]
After submitting a project, I saw this error message:

![Packagist](https://user-images.githubusercontent.com/1505719/115966340-1505b280-a525-11eb-8d20-139c9e2bb9f2.PNG)

Trying to submit it a second time gave the message "A package with the name phpopendocs/blank-project already exists.", and it is apparently listed now. So either it was a incorrect error message, or a comment about the status of the package.

**Comment by Seldaek** [comment]
This is due to:

```
Client error: `POST https://api.github.com/repos/PHPOpenDocs/BlankProject/hooks` resulted in a `403 Forbidden` response:
{
  "message": "Although you appear to have the correct authorization credentials, the `PHPOpenDocs` organization has en (truncated...)
```

It means that indeed the package was added correctly, it just failed while setting up the auto-update hook. Do you have any special settings on that organization? It appears to be related to OAuth app access restrictions https://docs.github.com/en/organizations/restricting-access-to-your-organizations-data/about-oauth-app-access-restrictions - if you can give me more info maybe I can reproduce and at least improve the user reporting on this.

**Comment by Danack** [comment]
> Do you have any special settings on that organization?

Not special, but looking at the Packagist application for my account on github, it appears that I haven't granted it access to the PHPOpenDocs organization which might explain it, I guess.

I can setup the auto-update hook by hand, and can grant access to that org, to make it work for me.

Do you want me to leave it as is for a bit, to make it easy to test against?

**Comment by Seldaek** [comment]
Nope feel free to fix the permissions and/or fix the auto-update hook, I think that's enough info to repro on my end. This isn't super high prio though.

**Comment by Danack** [comment]
> This isn't super high prio though.

[Agreed](https://youtu.be/wnY9kOkhjm4?t=11).
