### ISSUE TITLE
Version statistics data seems to be incorrect.

### ISSUE THREAD

**Issue by frankdejonge** [composer/packagist#1221]
Hi :)

I was just looking at the [versions data for Flysystem](https://packagist.org/packages/league/flysystem/php-stats) where I now see each of the version with an equal share, all around 7,7%. This seems statistically very unlikely. Seems more likely that the data is not being recorded/processed/queries properly.

Here is a screenshot of what I see:

<img width="275" alt="Screenshot 2021-11-28 at 20 48 31" src="https://user-images.githubusercontent.com/534693/143783667-84cce04c-3034-4ec5-851f-a651573d336b.png">

**Comment by Seldaek** [comment]
Yeah that looks like there was some data loss there.. Caused by https://github.com/composer/packagist/commit/995220d0b6e21d70a1b04ff1b18ccf1c989b0e9d which I thought was safe but eh looks like it wasn't.

Anyway it's busy catching up all packages now, should be back to normal but the data gap in the "all" version will remain as I don't have an easy way to reprocess that.

**Comment by stof** [comment]
This weird display also happens when there is no installs at all for a given date. See for instance https://packagist.org/packages/behat/mink-selenium2-driver/php-stats#1.5, which shows all PHP versions at 10% before the release date of the selected version
