### ISSUE TITLE
[FEATURE] Expose Version-README through API

### ISSUE THREAD

**Issue by j6s** [composer/packagist#1342]
**Background**

I am currently developing a tool that aggregates versions of packages used in an agencies projects. As such, I am using the composer v2 API to periodically look for new versions. This works fine, but having the README in the tool would be nice - that way potential changes in the package could be seen directly when viewing a potential package upgrade in my tool.

Unfortunately, the v2 API does not seem to provide information about the README - however, the following API-path to READMEs does seem to exist:

* The v1 API exposes a `uid` for each version
* This uid can be used in the `/versions/{uid}.json` endpoint

There are 2 problems with this, though:
1. The v1 API is deprecated
2. The versions API does not seem to be meant for public consumption

---

**Proposed Solution**
I propose the following changes, which should make it easier to fetch the READMEs without introducing big changes:

* Add the `uid` property to the v2 API
* Document the versions API (This also means that the API must be stable in the future, though)

I have not yet looked at the code that provides these APIs, but my understanding is that at least the v2 metadata is stored in static files, which in turn means that changing their schema requires all files to be regenerated, which may produce a lot of overhead just for this small change.

**Comment by glaubinix** [comment]
`/versions/{uid}.json` is used to render the version specific information, like package links, that is shown on the package page. It's called every time you click on a new version. The HTML content of that endpoint will change every time someone makes changes to that section, and using it in a third-party tool is probably not a good idea. It also doesn't contain the content of the README file.

Packagist only stores the content of the README of the default branch. There should be no need to add the `uid` to the v2 metadata. As far as I can tell, the README file is currently not exposed anywhere, so your best bet might be to add a new API endpoint to fetch the README, e.g. `/api/packages/{package}/readme`.

You might also be interested in `https://packagist.org/metadata/changes.json` which returns a list of packages that changed since the timestamp you pass. This should make it easier to know which packages updated since you last run your command.

**Comment by j6s** [comment]
Ah, interesting. To be honest, I didn't look at the payload that detailed: It was a request done with every version change that contained HTML. In that case, that's not what I am looking for.

**Comment by Seldaek** [comment]
Closing here as I'm not sure what to do. If anyone really cares for a readme endpoint it shouldn't be hard to send a PR.
