### ISSUE TITLE
Package Provider Data is Too Big

### ISSUE THREAD

**Issue by qiqizjl** [composer/packagist#1348]
We are still using Composer1. But it keeps prompting that there is not enough memory. After checking, I found that there are some oversized json files in the metadata of Composer1, and the packages inside do not seem to have much relationship with the packages I use.

eg:
https://repo.packagist.org/p/illuminate/http.json  42m
https://repo.packagist.org/p/illuminate/events.json  42m

**Comment by qiqizjl** [comment]
https://github.com/composer/packagist/blob/main/src/Package/SymlinkDumper.php#L228
https://github.com/composer/packagist/blob/51195adab23b779a96fd40faf618bfd8419c2c93/src/Entity/Version.php#L385

Looks like it's caused here. Does the metadata of Composer1 need to be processed for the replace package?

**Comment by stof** [comment]
The fact that all replacers were also included in those files was one of the known issues of the v1 format, which was fixed in the v2 format. The solution to reduce memory usage is to migrate to Composer 2.

**Comment by qiqizjl** [comment]
Our business has not been fully migrated to Composer2. Is the metadata update script of v1 no longer maintained?

**Comment by stof** [comment]
It is not that it is not maintained. It is that changing the structure of the metadata would break Composer v1 (which is why this needed to be done in a new format of metadata) and that the Composer v1 solver cannot consume the metadata in v2 format (due to the way the solver works, it needs those additional package info)

**Comment by qiqizjl** [comment]
tks
