### ISSUE TITLE
How to make packagist get the 'dist' reference for a public repo on a self-hosted gitlab instance?

### ISSUE THREAD

**Issue by Davigugu55** [composer/packagist#1379]
Hello,

I'm trying to publish a project that's available on our internal self-hosted gitlab, but when I publish it to packagist, all my versions "dist" receives the value "_unset".

What can I do so that the self-hosted dist url is known to packagist?

I've been trying it out on public gitlab.com, and it works as expected. As we can see in the [package .json](https://repo.packagist.org/p2/davi.ribeiro1/grogoo-restfier.json), it get's the correct url value, which is using the API to download the file:

```
{
  "version": "1.0.1",
  "version_normalized": "1.0.1.0",
  "source": {
    "url": "git@gitlab.com:davi.ribeiro1/grogoo-restfier.git",
    "type": "git",
    "reference": "5eeb414150e8fd13888f4a8866a6fd7419e50540"
  },
  "dist": {
    "url": "https://gitlab.com/api/v4/projects/davi%2Eribeiro1%2Fgrogoo-restfier/repository/archive.zip?sha=5eeb414150e8fd13888f4a8866a6fd7419e50540",
    "type": "zip",
    "shasum": "",
    "reference": "5eeb414150e8fd13888f4a8866a6fd7419e50540"
  }
}
```

For my self-hosted gitlab, my [package .json](https://repo.packagist.org/p2/davi.ribeiro/grogoo-restfier.json) gets the value below:
        
```
{
  "version": "1.0.1",
  "version_normalized": "1.0.1.0",
  "source": {
    "url": "https://gitlab.jdrel.com.br/davi.ribeiro/grogoo-restfier",
    "type": "git",
    "reference": "5eeb414150e8fd13888f4a8866a6fd7419e50540"
  },
  "dist": "__unset",
  "time": "2023-05-18T19:43:53+00:00",
  "extra": {
    "laravel": {
      "dont-discover": []
    }
  }
}
```

Both API values are accessible anonimously from:

- Public Gitlab:
https://gitlab.com/api/v4/projects/davi%2Eribeiro1%2Fgrogoo-restfier/repository/archive.zip?sha=5eeb414150e8fd13888f4a8866a6fd7419e50540

- Self-hosted Gitlab:
https://gitlab.jdrel.com.br/api/v4/projects/davi%2Eribeiro%2Fgrogoo-restfier/repository/archive.zip?sha=5eeb414150e8fd13888f4a8866a6fd7419e50540

**Comment by stof** [comment]
Composer will know how to use the Gitlab API to get the metadata in an optimized way and to download code archives only if the domain is in the list of configured gitlab domains (composer does not have a way to automatically detect whether a particular domain is a self-hosted gitlab instance): https://getcomposer.org/doc/06-config.md#gitlab-domains

packagist.org uses the default configuration for that, so only `gitlab.com` is supported as a gitlab domain but not `gitlab.jdrel.com.br`

Side note: the actual metadata does not have `__unset` as value, but rather no dist property at all. This `__unset` value is due to the metadata minification done using https://github.com/composer/metadata-minifier

**Comment by Davigugu55** [comment]
Alright, I see this is a composer configuration problem. Thanks for the help @stof

**Comment by stof** [comment]
Well, if you want to have the dist URLs available when using the packagist.org metadata, it would require changing the composer config used by the packagist.org servers, not your local configuration.

**Comment by Davigugu55** [comment]
That means there is no way to configure it on my side right?

I believe the workaround for this case would be creating a public repo on gitlab.com that mirrors the one on my self-hosted then.
