### ISSUE TITLE
extend GitLab support

### ISSUE THREAD

**Issue by madbob** [composer/packagist#1406]
Would be nice to improve support for GitLab, displaying number of stars, issues, forks and whatever as already happens for GitHub.
Can be pretty easy with the support of Composer, which already collects those metrics using GitLab's API, but the GitLab driver do not exposes the raw data (as the GitHub driver does). Here is [a pull request](https://github.com/composer/composer/pull/11734) to permit this, and unlock further developments on Packagist.

**Comment by Seldaek** [comment]
Fixed by https://github.com/composer/packagist/pull/1408

It works for me in my dev env but not yet on prod, because we appear to be using git clone fallback I suspect because we fail authentication from GitLab, so the API is not used and this fails.

I'll have to dig into this further to see if we can fix it..

**Comment by Seldaek** [comment]
Alright figured it out, fixed now, whenever GitLab packages update they should receive the new info.
