### ISSUE TITLE
Syntax Highlighting in README.md seems not to work properly when coming from Bitbucket

### ISSUE THREAD

**Issue by Moskito89** [composer/packagist#1447]
I assume that syntax highlighting in a `README.md` file seems not to work properly when the repository comes from Bitbucket.

Here are to libraries to compare:

*   From GitHub: [solaris/php-moon-phase](https://packagist.org/packages/solaris/php-moon-phase)
*   From Bitbucket: [bitandblack/sentence-construction](https://packagist.org/packages/bitandblack/sentence-construction)

In both of them, the PHP code has been written with three backticks, followed by `php`. 

Strangely enough, the HTML of the rendered documents is different: 

From GitHub:

```
<pre><span class="pl-ent">&lt;?php</span>
<span class="pl-k">use</span> <span class="pl-v">Solaris</span>\<span class="pl-v">MoonPhase</span>;
[…]
</pre>
```

From Bitbucket: 
 
```
<pre><code class="language-php">&lt;?php
use BitAndBlack\SentenceConstruction;
[…]
</code></pre>
```

Has anyone an idea what happens here and why?

**Comment by glaubinix** [comment]
Code syntax highlighting currently only works for GitHub repositories. For GitHub repositories, Packagist uses the GitHub API to fetch the rendered HTML of a readme file. For all other repositories a [cebe/markdown](https://packagist.org/packages/cebe/markdown) is used to render the markdown as HTML which doesn't seem to support code syntax highlighting.

**Comment by Moskito89** [comment]
Oh, interesting! Thanks for the explanation, @glaubinix! I thought we'd be using something like highlight.js here... What were the reasons against solving this on the front-end side?

**Comment by glaubinix** [comment]
I don't know, but I would assume that the GitHub API call is convenient, covers >95% of installed packages without the need for an additional dependency. So far the lack of code syntax highlighting in other repositories probably just hasn't come up yet.

**Comment by Seldaek** [comment]
Yeah it just works and GitHub is almost 99% of packages, so not really worth the hassle to fix IMO. We have so many other things to do.

**Comment by tflori** [comment]
once I fixed that readmes would be loaded from non-github packages. IIRC the highlighting worked back then, did it not?

@Seldaek maybe 99% of the packages come from github because of the README issuess. In my opinion it is a mistake to force people to github (I'm writing gitlab-ci jobs since 2012 - they would still work today. The shinanigans on github are a maintenance nightmare for open source software)

**Comment by stof** [comment]
@tflori syntax highlighting never worked for non-github sources, due to the implementation which is described in https://github.com/composer/packagist/issues/1447#issuecomment-2082624075
Packagist does not have a syntax highlighter in its markdown renderer. For github packages, the syntax highlighting is provided by github itself.
