### ISSUE TITLE
Rendering issue when using search on `/extensions`

### ISSUE THREAD

**Issue by TimWolla** [composer/packagist#1474]
![image](https://github.com/user-attachments/assets/bf0a58e1-6c1f-41aa-ad5e-ecd12c42cb35)

Note the misaligned “PHP Extensions” header.

**Comment by stof** [comment]
this is cause by the negative top margin (`-5px`) on the heading. Because of that, it overlaps with the previous row containing the Algolia logo. As this row contains a floated element taking 75% of the width, the content starts after that floating element (which corresponds to the space reserved for the right column, where there is no element in that row).

This does not happen when using the search on a package page because on such page, the `.title` element with a negative margin is nested into other containers, including a `.row` element that is clearing floats.
