### ISSUE TITLE
Gittip Support on Packagist

### ISSUE THREAD

**Issue by clone1018** [composer/packagist#267]
[Gittip](https://www.gittip.com) is an [open-source](https://github.com/zetaweb/www.gittip.com) platform for sustainable crowd-funding. Gittip lets you set up small weekly anonymous donations to people who do great work. It's particularly well-suited for open source programmers and projects. 

Integration would Gittip would be super simple, I'm working on the Gittip Anywhere plugin for Google Chrome which adds support for Gittip on your favorite sites (right now GitHub): 
![Gittip Anywhere](http://puu.sh/1MpWT.png) 

We've added a Gittip link under Maintainer, like: 
![this](http://puu.sh/1MpYh.png) 
but of course implementation design is up to you guys (buttons are cool too!).

Anyways, looking forward to hearing back soon!

**Comment by mhujer** [comment]
Meanwhile, the gittip was renamed to gratipay.

And the link to it was added to RubyGems https://github.com/rubygems/rubygems.org/issues/500 and then it was removed in 2014 https://github.com/rubygems/rubygems.org/commit/78289062c134fa2b0f760571638b8dd9e6789151 (if favor of `Linkset` instead of specific service https://github.com/rubygems/rubygems.org/issues/500#issuecomment-65150164)

If "tipping" for developing open-source packages takes off it may be better to have something like `"donation"` field in `composer.json` to be platform independent.

So I guess this issue can be closed for now, right?

**Comment by Seldaek** [comment]
Yup we can probably close until further notice..
