### ISSUE TITLE
[Feature] Ability to order by downloads on most actions

### ISSUE THREAD

**Issue by dmyers** [composer/packagist#316]
If you go to popular the download counts are all over the place.

I cloned the repo and it loks that downloads are stored in meta. Is there a way to check a GET param for order and see if it is set to downloads and sort based on that?

**Comment by sanchitbh** [comment]
I think this should be left for the users to decide. If i want to sort my results by number of downloads then it should let me. I'm really missing this feature. Sorting by download really helped me find the best results quickly, now it's all messed up and i have to open packages with 11 downloads before i'm able to find anything useful.

**P.S.** The sort by downloads was also super helpful for new developers in knowing what most people are using, which is sort of a clue which package developers trust the most. I would have never discovered symfony's components if this feature was not there. *Please consider putting it back because it was incredibly helpful feature.*
