### ISSUE TITLE
oAuth Security Issue

### ISSUE THREAD

**Issue by steefaan** [composer/packagist#441]
I aleady sent you an email to avoid the usage of an open bug tracker but I didn't get any response yet so I need to write it down here. Some days ago I submitted some packages to packagist with an oAuth authentication through github. After some time of inactivity packagist logged me out automatically. I clicked again the Login with Github button and suddenly I was logged in as a different user (https://github.com/admad in this case) and was able to change all the packages (complete admin rights). I'm not able to reproduce this bug but it seems to be a critical issue in your oAuth authentication and should be fixed soon. Please take a look on the picture. I will be available through github or the mail which I have sent you for further questions.

![security](https://cloud.githubusercontent.com/assets/5982785/4043559/7153f6dc-2d13-11e4-8827-26155313a494.png)

**Comment by ArthurHoaro** [comment]
I had the same issue today. I logged in using Github OAuth and I was on another user account.
I'm not sure what can be done about this, but even if it's very rare, this issue should be addressed.

Since this issue has been closed 5 years ago, let me know if I should open another one.

![screenshot](https://pbs.twimg.com/media/EBmy7yXW4AEfMce?format=png&name=large)

**Comment by Seldaek** [comment]
Hey, so I think I figured out what happened here in this case..

When doing oauth login, there is a request to verify the token we get in the URL, then we get a github token and with that the user info is fetched from github (by HWIOAuthBundle) then finally it goes into our code which loads the user by github ID at https://github.com/composer/packagist/blob/48d4f965f75726eef3caa26407e5241710a838c8/src/Packagist/WebBundle/Security/Provider/UserProvider.php#L63 

Now the problem is if this second request to get the user info fails, you'd think HWIOAuthBundle would fail hard but I think we hit a case where it goes through and we load here a user with `githubId => null`, which turns out to load @hidenorigoto's account as he has githubId NULL and is the first user in the DB which does.

The fix should prevent this from happening if this oddball situation occurs again, sorry about that @hidenorigoto.
