### ISSUE TITLE
Support for Composer package in sub-directory of GitHub repo

### ISSUE THREAD

**Issue by bdferris** [composer/packagist#472]
I have a multi-language project in a GitHub repo (https://github.com/google/gtfs-realtime-bindings/) that has a php/ subdirectory containing a composer.json file.  Best I can tell, there is no way to generate a Packagist package from my repo given this configuration.  Any chance this is a scenario you would consider supporting?

**Comment by Seldaek** [comment]
This is very unlikely because it'd be kinda hard to find those files via the github API unless we do a full listing of all dirs and that'd slow down all our updates quite a lot.

**Comment by Rastusik** [comment]
what about manually setting the path in a form on the packagist server?

**Comment by sffc** [comment]
Please reopen this issue.  This restriction causes major headaches for both users and maintainers of composer projects.

**Comment by buffcode** [comment]
This would also help with MonoRepos such as symfony/symfony as the projects would not necessarily needed to be split up into single repositories.
In our use case we have a mono repository with ~20 internal projects which should be able to be installed independently. In order to install them, we have to split them into separate repositories and publish them.

Using `git clone --filter` or sparse checkouts in combination with the path input (https://github.com/composer/packagist/issues/472#issuecomment-171307013) would result in a valid composer project.

**Comment by stof** [comment]
@buffcode given that packagist does not generate its own archives but relies on the github archives for downloads, downloading components directly from the mono-repo would not be possible. This would require a major change in the architecture of packagist to allow that.

**Comment by edertone** [comment]
> @buffcode given that packagist does not generate its own archives but relies on the github archives for downloads, downloading components directly from the mono-repo would not be possible. This would require a major change in the architecture of packagist to allow that.

Time to start looking for better dependency management alternatives then. It is sad to see how composer is years behind other systems like NPM in terms of features and flexibility

**Comment by JoanBotella** [comment]
I think it is important to allow having the composer-related files and directories in a project subdirectory, in order to avoid a root directory full of unorganized configuration files. Maybe it could be done using a composer.json directive or through some kind of form on Packagist. For example, on creating the package on Packagist, alongside with the remote repository URL the composer.json path could be asked too.

**Comment by Marat-Tanalin** [comment]
@Seldaek
> This is very unlikely because it'd be kinda hard to find those files via the github API unless we do a full listing of all dirs and that'd slow down all our updates quite a lot.

Does this matter when a developer [submits](https://packagist.org/packages/submit) a specific package URL to Packagist manually anyway?

Instead of:

    https://github.com/developer/project

we could just submit a subdir URL:

    https://github.com/developer/project/tree/master/subdir

**Comment by nextgenthemes** [comment]
Probably an off-topic question but this seems to be about packagist. Is there any way to do this with composer with code from GitHub I have full control over? Meaning I can place the `composer.json` in root or also in the dir I actually want to install?

Composer has something like post install scripts I think. Maybe there is a way to do this for code that is actually NOT on packagist?

Or maybe there is some workaround? I guess I could configure a package to install into `/tmp` and then just copy the desired folder.

**Comment by lcdss** [comment]
This would be really great for monorepos e doesn't need to slow down anything if the `url`  will give all the info needed.

**Comment by Furgas** [comment]
Dang, and I was excited I could switch to GIT and won't need tons of readonly repos with my monorepo and tools to synchronize them. Maybe I will stay with Subversion as composer supports this feature with "package-path" (so it is not a new concept).

**Comment by Furgas** [comment]
[Here](https://github.com/sdoatput/composer/tree/package-path-for-git) is the quick&dirty patch adding "package-path" to "git" repository. I'm using Satis and it works well there. It requires [git filter-repo](https://github.com/newren/git-filter-repo) installed.

**Comment by zolex** [comment]
it is possible with a little workaround:

just place a composer.json similar to this one in the project root:

    {
        "type": "project",
        "name": "my/package",
        "license": "proprietary",
        "minimum-stability": "stable",
        "prefer-stable": true,
        "scripts": {
            "post-create-project-cmd": [
                "rm -rf composer.json vendor",
                "composer install -d path/to/folder/with/composer.json/in/it"
            ]
        }
    }

**Comment by stof** [comment]
@zolex this might work when the *project* is in a sub-directory (and your package is only used as a template to start the project). But not for packages meant to be used as dependencies

**Comment by ijry** [comment]
other lang all support pub a subdir as a extention to package manager，such as  java/node/python/.net，reallly need this feature.

**Comment by LLyaudet** [comment]
Hello @Seldaek :)
This was closed more than 9 years ago but we are still many to think it would be needed.
Any chance you may revert your decision ?, especially now that a similar code has been done
by @vtsykun in packeton : https://github.com/vtsykun/packeton/issues/68 ?
Thanks if you take the time to answer us, best regards,
    Laurent Lyaudet

**Comment by edertone** [comment]
agree

**Comment by ijry** [comment]
agree

**Comment by djvickx** [comment]
There is one way to achieve it, you can use **.gitattributes** files and you can define in that file those folders/files that you want composer to ignore at the time when someone requires the library in the project. 
Like e.g. if you add the following line in **.gitattributes** file:
`tests           export-ignore`
It will ignore the tests folder and all those files/folders mentioned in the file will be a part of your library source code but those won't be included by composer at the time user downloads the library.

**Comment by LLyaudet** [comment]
Hello @djvickx ,
I don't think what you suggest is a true solution.
It still requires to add files at the root of the git repository,
instead of having composer look only in the dedicated subfolder.
A true solution is still needed.
Best regards,
    Laurent Lyaudet

**Comment by djvickx** [comment]
Hi @LLyaudet, I agree its not a true solution and it doesn't work for the sub directories in case of composer file is in a sub directory but its a work around atleast to remove files/folder on the same root level.

**Comment by vtsykun** [comment]
Hi @LLyaudet 

To support this function by Packagist.org, changes will be required from GitHub API. Currently zipball GitHub api does not allows downloads source code archives for specific path prefix in git repository. 

But Packeton in first clone git repository to local cache and use command `git archive --prefix=path_pref` to build archive for monolithic repo locally. This approach is not very applicable for public repositories like Packagist.org due to problems with horizontal scalability and infrastructure cost

**Comment by LLyaudet** [comment]
Hello @vtsykun

> This approach is not very applicable for public repositories like Packagist.org due to problems with horizontal scalability and infrastructure cost
I don't have all the elements to see if you're right or if you're wrong.
But I know two things:
- Adding the feature needed in GitHub Api should not be hard;
- Otherwise it is easy to have another process included in packagist to upload a package manually exactly like you do in PyPI.
Easy solutions exist, no solution is from people don't want some solutions.

Best regards,
     Laurent Lyaudet

**Comment by mcmillenb** [comment]
Just fyi for folks like me who couldn't imagine this not being technically possible: paying for Private Packagist gives you this feature

> Private Packagist supports multiple packages per VCS repository, but you'll need to specify where the composer.json files are located.
> 
> When adding a new package, select the option Repository contains multiple packages or composer.json is located in a subdirectory. You can either specify the path to the composer.json file directly (if you have a single package in a subdirectory), or use a glob pattern such as {lib,src}/**/composer.json to specify multiple locations.

https://packagist.com/features/private-vcs-packages?section=features

**Comment by chascode** [comment]
It'll be great if composer natively supported sub packages.

    require { "foo-vendor/foo-package/sub-package": "^1.0" }

...and foo-package's composer could look like:

    subpackages: ["packages/*"]

This would make both mono repositories and large projects split into smaller modules easier to maintain.

**Comment by stof** [comment]
@chascode allowing multiple `/` in a package name would cause conflicts in the vendor folder when having to install both `foo/bar` and `foo/bar/baz`, as one package would end up being written inside the install path of another one. There a good reason why composer enforces having exactly 1 `/` and npm enforces having either no `/` with a name not starting with `@` or a single `/` with the namespace starting with `@` (which guarantees no conflict between the namespace folder and unnamespaced packages).

Supporting mono-repos as the source of packages is a separate thing (there is nothing forcing to use multiple `/` for package names handled in a mono-repo). packagist.org does not support mono-repos because it relies on the archives generated by GitHub, and GitHub does not support generating an archive for a sub-path of a git repo.
Private Packagist supports mono-repos directly because it can solve that issue thanks to the fact that it is hosting its own code archives.
Note that packagist.org is unlikely to move to hosting archives instead of using the GitHub (or GitLab) archives because that would require a huge amount of bandwith and storage, for which the project probably does not have the resources.

**Comment by chascode** [comment]
@stof I see what you're saying.

Instead of `foo/bar/baz`, maybe `foo/bar#baz`.  Since `#` is currently an illegal character in package names there shouldn't be any backward compatibility issues.

For namespace conflicts:

    <project root>/vendor/foo/bar
    <project root>/vendor/foo/bar#baz

I was imagining the composer client itself handles sub packages:

1. Fetch package meta from packagist (as it currently does).
2. Use git's sparse checkout to only download file content as and when required.
3. Sync files from `~/.cache/composer` to project accordingly.

There's still a few more problems to solve but that's the gist of my idea.

**Comment by stof** [comment]
@chascode `#` is not allowed in URLs without encoding, which would be a mess for URLs to load metadata.
And anyway, we don't need an automatic convention anyway. Your packages can have an explicit name in their composer.json.

> 2\. Use git's sparse checkout to only download file content as and when required.

this does not work for any of the existing supported installation method of composer:

- installing from source keeps the `.git` folder in the vendor folder, which is useful when you want to hack development on your dependency. this requires having the structure of the whole git repo, not just a subpath
- installing from dist expects to download an archive (that is cached as is), which is the default behavior because downloading an archive is a lot faster than cloning a git repo (even for a sparse checkout, as this still fetches the git history)

So this would be a huge project.

**Comment by stof** [comment]
@punyflash it is **not** a fork of packagist.org with similar needs. It handles hosting of code archives, making it closer to Private Packagist.

The root cause for not supporting mono-repos in packagist.org is that packagist.org does not host code at all. It relies on dist archives exposed by GitHub or GitLab, and those don't support downloading an archive containing only a subfolder of the repo.
And packagist.org cannot handle hosting of code on its own (that would require massive infrastructure, which would require massive funding)

**Comment by offizium-berndstorath** [comment]
@stof I do understand your point. But doesn't crates.io, pypi, npm exist? They are able to have their own index. Php is backed by a Foundation with sponsors, how are they not able to provide the funds?

go afaik also does not have its own index (only a proxy) and they make sub dirs work seamlessly

**Comment by Seldaek** [comment]
Looks we are aware of this, we have some plans to improve things eventually (on Packagist at least, on Composer custom repos is a whole different beast and way less relevant IMO), stop bickering here it is not helping anyone.
