### ISSUE TITLE
A dot (.) in package name possibly causing a 404

### ISSUE THREAD

**Issue by samayo** [composer/packagist#504]
So, I have a repo called [country.json](https://github.com/samayo/country.json), and decided to throw in a `composer.json` file, went on to my profile and submitted `https://github.com/samayo/country.json` without any problems, but then [{"status":"error","message":"Package not found"}](https://packagist.org/packages/samayo/country.json) occurred. Is this due to the  dot **`.`**? what is the best way to get past this?

**Comment by stof** [comment]
hmm, the issue here is that ``https://packagist.org/packages/samayo/country.json`` is also the URL to display the page of the package ``samayo/country`` in JSON format.

Having a dot in the package is not an issue on Packagist. But there is an issue if the package name ends with ``.json`` or ``.html``

**Comment by samayo** [comment]
Yeah, so I ought to rename the package without dots. Thanks

**Comment by samayo** [comment]
sorry for reopening this, but is there any workaround for this?

**Comment by hkdobrev** [comment]
I think this is a problem in https://github.com/composer/packagist. Packagist could make it so the URL for such packages to be `https://packagist.org/packages/samayo/country.json.json`.

**Comment by stof** [comment]
@hkdobrev this is what the JSON url for ``samayo/country.json`` will look like. but the URL ``https://packagist.org/packages/samayo/country.json`` will match the route with ``samayo/country`` as package and ``json`` as format, not ``samayo/country.json`` as package and nothing as format, and then the controller will say that the package ``samayo/country`` is not found.

The hard part is that ``/packages/samayo/country.json`` can match the route regex in 2 different ways, and none will give a working result for all cases (if we rewrite the regex to prefer putting the ``.json`` in the package name rather than in the format, it will break things for all packages when accessing their page in JSON format).
The only ways to have something working all the time are:
- having a separator between the package name and the format using a character which is not allowed in package names. But the dot is the only meaningful char there (note btw that dots were not allowed in composer package names initially, so there was no such issue)
- force using the format explicitly for HTML versions of packages instead of using ``/packages/{package}``. The issue is that this is too late. Making the format mandatory means breaking all existing URLs.

Note that you should be able to access your package page as ``https://packagist.org/packages/samayo/country.json.html`` (but Symfony will not add the ``.html`` suffix when generating URLs because it is the default format)

**Comment by jvasseur** [comment]
https://packagist.org/packages/samayo/country.json.html wouldn't work, the only format allowed in the url is json, and when not present it default to html.

**Comment by stof** [comment]
And I'm wrong. the route definition forbids adding the ``.html`` explicitly. I should have checked *before* posting

**Comment by stof** [comment]
this means I don't see any BC way to have Packagist working for package names ending in ``.json``

**Comment by samayo** [comment]
Prior to this, I have thought that package names ending with `.json` would work in packagist, because it seems reasonable to expect there might be many repos out there that end with `.json` just as there are many with `.js`

**Comment by hkdobrev** [comment]
@stof The routes could be made greedy and catch everything and then the application logic could get the last matching `.json` as the format and checking what actually packages exist. The problem is that it wouldn't allow `country` and `country.json` in the same vendor, but this could be made BC for existing packages (to catch the `country` package first). There may be a better way, but there is a way at least.

**Comment by Seldaek** [comment]
Given how rarely this happens, I think the best is to simply prevent package names called `.json` at submission time to avoid issues.

**Comment by stof** [comment]
@Seldaek how many such package is there in the database currently ?

**Comment by Seldaek** [comment]
@samayo's package is the only one.

**Comment by samayo** [comment]
I guess this settles it. If it is possible to remove this package from my packagist repos list, it would be nice .. as I can't do it by my self.

**Comment by Seldaek** [comment]
Sure I'll do that, and I'd suggest you just rename it to `samayo/country-data` or such, I don't think the fact that it's json needs to be in the name, it's kind of an implementation detail :)

**Comment by samayo** [comment]
Yeah, been thinking about that lately. I was going for `/worlddb` .. but `/country-data` sounds a better choice. Thanks.

**Comment by cnxh** [comment]
@Seldaek the package "samayo/country.json" is still existing in Packagist, could you please to remove it?

**Comment by Seldaek** [comment]
Done
