### ISSUE TITLE
outdated symfony version blocks composer lib update

### ISSUE THREAD

**Issue by davidverholen** [composer/packagist#519]
Since composer alpha 10 requires symfony console ~2.5 and packagist requires symfony ~2.3@dev composer is installed in version alpha 9 and can't be updated.

Updating symfony modules for packagist seems to work (i will keep testing a bit):

"symfony/symfony": "^2.3",
"symfony/assetic-bundle": "^2.3",
"symfony/swiftmailer-bundle": "^2.3",
"symfony/monolog-bundle": "^2.4"

**Comment by stof** [comment]
If you use composer, you should only install from lock anyway. Projects have their dependency locked.

and there was an attempt to migrate to 2.7 a few days ago, which was reverted because of a performance issue: https://github.com/composer/packagist/commit/a627630d6caa044b4bb85a8e38ad832266ba64b7
The migration will need to be done again but not at the same time than the redesign to give more time to investigate the issue.

**Comment by davidverholen** [comment]
ah O.K., dit not see the migration attempt. I need composer alpha10 in my setup, but since it will be migrated anyway I can update composer manually till it's done, thx for fast response!
