### ISSUE TITLE
Allow all logged in users to click update

### ISSUE THREAD

**Issue by thiemowmde** [composer/packagist#522]
Reopening #521.

That answer in #521, ... What the ...? "I deny to see a problem, do not disturb my circles".

This issue is [causing pain in our team for months now](https://phabricator.wikimedia.org/T96659) and the solution is so incredible simple, it's just painful. Just make the button clickable for logged in users, no matter if they are maintainers or not. It's very, very easy to prevent logged in people from "hammering this button". This can't be a reason to deny having a workaround for an issue that exists and is reported continuously.

**Comment by Seldaek** [comment]
If you don't want me to close it then you gotta explain the problem clearly. Pointing at other closed issues isn't really good enough.

Can you identify what in the wikimedia release process is causing such issues that nobody* else seems to encounter? Is it because you push tags without commits that the hook doesn't get triggered? If so maybe we can fix the hook to also trigger on tag pushes? Again, I'd like to know *what* is going wrong so that we can *fix* it. Computers are here to make boring tasks like clicking buttons repeatedly unnecessary, if we really can't fix it then I'll consider the button solution, but right now it still sounds to me like the easy way out, and pushing back the problem on humans.

*almost nobody, probably nobody, maybe nobody, anyway not a massive amount of people reporting it..

**Comment by stof** [comment]
I think there is indeed an issue if you tag a release on a commit which is already in the repo. AFAIK, this does not trigger any webhook (the ``push`` webhook is only triggered when a new commit is actually pushed to a branch, not when a tag is pushed for an existing commit in the repo). Btw, Bitbucket suffers from the very same issue.
I guess we need to add the ``create`` event too

**Comment by stof** [comment]
See the PR updating the github service

**Comment by stof** [comment]
OK, looks like we need to change the way the github hook works by setting a webhook through the API instead of using a service hook, due to their policy.

**Comment by Seldaek** [comment]
Ok that makes sense and it would be a better UX anyway and bring our rate of auto-updated packages to a much higher level (github is ~97% of packages).

**Comment by JanZerebecki** [comment]
Is the webhook fire and forget? I.e. if for some reason github receives a http status 503 does github retry?

**Comment by teohhanhui** [comment]
1. Outdated `version` field was specified in [composer.json](https://github.com/paragonie/random_compat/commit/d6efc0a466f973cdf8235fc3a53dfc022354c32c#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R4)
2. I sent a [PR](https://github.com/paragonie/random_compat/pull/26) to remove that and it was merged
3. Packagist picks up latest commit in [dev-master](https://packagist.org/packages/paragonie/random_compat#dev-master) but not the missing version (previously [tagged](https://github.com/paragonie/random_compat/releases/tag/v0.9.6))

**Comment by alcohol** [comment]
They will have to update the tag yes.

**Comment by Seldaek** [comment]
This has been added some time ago
