### ISSUE TITLE
404 error cached

### ISSUE THREAD

**Issue by rentalhost** [composer/packagist#545]
I created a bitbucket repo, but I forget to push from local to remote. So I tried to submit it to packagist and, obvious, I get a 404 error, like:

> We had problems parsing your composer.json file, the parser reports: The "https://bitbucket.org/USER/REPO/raw/master/composer.json" file could not be downloaded (HTTP/1.1 404 NOT FOUND)

So I pushed but the 404 error seems been cached. I put a "www" before domain, and it worked again. Without "www" continues returning a 404 error.

**Comment by rentalhost** [comment]
**File exists**: https://bitbucket.org/rentalhost/vanilla-result/raw/master/composer.json

**Comment by Seldaek** [comment]
If I try to submit https://bitbucket.org/rentalhost/vanilla-result.git right now it seems to work, so I am not sure if either you had a wrong URL or the cache was on the bitbucket side perhaps? But if we had a cache bug on our side the issue would still be there I think because AFAIK all our repo caches are caching forever.

**Comment by rentalhost** [comment]
Not cache forever. On next day it worked perfectly. It cache only by some hours, maybe.

**Comment by Seldaek** [comment]
Yeah I think that might just be an issue with bitbucket's API.
