### ISSUE TITLE
GitHub autoupdate not working

### ISSUE THREAD

**Issue by matiasperrone** [composer/packagist#561]
Hello,

I have a package on GitHub https://github.com/aluguest/ical-easy-reader, I added the service:

![packagist - github com](https://cloud.githubusercontent.com/assets/2567511/9237241/3e0fe6ec-4120-11e5-84a0-35a0c0cd57a9.png)

The package URL is https://packagist.org/packages/aluguest/ical-easy-reader

I'am on the 1.4.1 version and is not working propertly, shows version 1.3.2. I have created two tags "v1.4.1" and "1.4.1" non of those works....

I deleted the package on packagist and re-created (with the same name), renamed the two GitHub and with packagist with the same names, I can't find the issue.

Please help!

**Comment by stof** [comment]
@matiasperrone the issue is that you have an explicit version in your composer.json, and it does not match the version of the tag, making the metadata invalid for the tag.
you should never use the explicit version when the composer package lives in a VCS repo. It brings no benefit at all, and can cause issues.
