### ISSUE TITLE
Packagist takes a long time to update the package information

### ISSUE THREAD

**Issue by rentalhost** [composer/packagist#589]
It occur in 20% of times that I submit a new tag. After I pull it to server (on my case, Bitbucket), Packagist, even after press 'update', don't show current version. On Bitbucket I can see normally the tag. Even if I use dev-master, it'll not work. 

Seems that Packagist don't get in realtime the repository status, or maybe Bitbucket is sending a cached response to Packagist, I don't know. In some cases, I need to wait about 30 minutes for the update to complete.

---

Off-topic: there are some way to force composer to do this check by passthrought the Packagist?

**Comment by felixgirault** [comment]
I often bump into the same issue, having to wait some time before the update is taken into account.
But today I did tag a project 4 hours ago, and packagist still doesn't reflect the changes.
I tried to update it through the GitHub web hook, the "update" button on the website, and the manual hook, but none of that worked so far.

Is there a particular problem right now ?

**Comment by stof** [comment]
@felixgirault which project is it ?

**Comment by felixgirault** [comment]
@stof https://packagist.org/packages/fg/parkour
Maybe I missed something but I'm really stucked at this point.

**Comment by stof** [comment]
The issue is that your composer has ``"version": "1.0.0"``. when the composer.json has an explicit version which does not match the tag name, Composer considers the tag as invalid. And this means that Packagist will never pick the 1.1.0 tag (it relies on Composer internally)

The general rule is to never specify the version explicitly when your package is hosted in a VCS repo:
- it is totally ignored for branches (the branch name is used, and the branch-alias if there is one)
- it can only create issues for tags.

**Comment by felixgirault** [comment]
OK that was such a stupid mistake... Thank you :)
To get back on the main subject, this time the update was instantaneous.

**Comment by Seldaek** [comment]
Not sure what to say here, I heard of a few cases where bitbucket seems to not notify us or their API is serving us stale data I am not sure. There is only anecdotal evidence of this. Unless someone can research it some more and find clear ways to reproduce issues it's kinda impossible to improve.
