### ISSUE TITLE
How can we import existing tags / releases?

### ISSUE THREAD

**Issue by DanielRuf** [composer/packagist#606]
The GitHub repository has several releases / tags but how can they be imported?

https://github.com/Maikuolan/phpMussel/issues/73

**Comment by stof** [comment]
they cannot be imported as they don't have a composer.json to define the metadata of the version.

You should make a new release supporting composer.

Btw, I saw that many of your old tags are named like ``v0.6e``. Letters to denote patch releases are not supported by composer, so such tag would not be available through composer. I suggest you to use semver names for patch releases: ``0.8.1`` instead of ``0.8a``

**Comment by DanielRuf** [comment]
Okay, thanks for the clarification.
