### ISSUE TITLE
Can't update package for more than half year

### ISSUE THREAD

**Issue by wodCZ** [composer/packagist#642]
Hello,
I have package registered on packagist from public GitHub repository.
Link: https://packagist.org/packages/wodcz/sandbox
Repo: https://github.com/wodCZ/sandbox/releases

As you can see, latest version on packagist is 2.0.0, released on 26. Jun 2015.
Next release (2.0.1) was on 1. Jul 2015, but it's not on packagist.

 - I've had hook properly configured.
 - I tried manually updating package on packagist - didn't work.
 - I also tried deleting package and creating it again - didn't help.
 - Then I configured and ran hook again - didn't change anything.

I'm not sure what can be wrong, or what I do wrong. 
I'm ok with renaming repository+package on GitHub, would that help me get proper versions on packagist?

Thank you.

**Comment by stof** [comment]
The issue is that your 2.0.1 tag contains ``"version": "2.0.0"`` in its composer.json. A mismatch between the explicit version and the tag name makes the tag invalid for Composer and so it will ignore it.
This is precisely why the composer doc (and the validate command) recommend to omit the version entirely when your package is managed in a VCS repo. the explicit version can only cause harm in this case, without any benefit (it is needed in other cases).

This is not an issue in Packagist.

**Comment by wodCZ** [comment]
Oh.. facepalm...

Thank You stof, closing.
