### ISSUE TITLE
Allow packages to be marked as "not listed"

### ISSUE THREAD

**Issue by pthreat** [composer/packagist#670]
I'm developing a big project, which depends on other subprojects which I'm also developing.

For this reason, I decided to use composer and packagist. 

It was unknown to me that every packaged posted in packagist was there as publicly listed. As soon as I posted my development packages I looked for an option to unlist them from the public eye, but no option was found, I thought this option would exist (I should've checked before).

I just needed to host my packages in packagist to use them anywhere through composer.

I do know about SATI but I feel like this could be a good feature for packagist.

Could you add a configuration option to mark certain packages as "out of the public view", so, only the developers with the proper package name would be able to use said package?

Kind regards.

**Comment by stof** [comment]
Given that composer needs a list of packages available in the repository (to know that it can get some metadata about the package from this repository), this cannot be implemented without re-architecturing Composer itself.

If these packages are intended to be used only by your team, use either Satis or Toran Proxy for that rather than publishing them on packagist.org

**Comment by pthreat** [comment]
They are intended to be used by the public but they are in a process of being developed.

**Comment by Seldaek** [comment]
IMO it's no problem to have them listed publicly even if they are in a pre-release state. If you put them up there it's to have them seen, if people want to use pre-release stuff it's up to them they should know the risks. If you don't want it there, just delete it and use vcs repos or other.
