### ISSUE TITLE
composer require is very very slow

### ISSUE THREAD

**Issue by agauniyal** [composer/packagist#676]
Could anyone take a look at this - https://github.com/mikecao/flight/issues/261

**Comment by stof** [comment]
``composer require`` implies doing a partial update to actually update the project dependencies rather than just updating the composer.json file (unless you specify ``--no-update``).
And currently, a partial update takes the same time than a full update, because a potential optimization is not yet implemented in composer. See https://github.com/composer/composer/issues/3672 for the discussion about it.

In any case, this is not an issue in Packagist but in Composer

**Comment by agauniyal** [comment]
I'm going to plain old git clone for now.
