### ISSUE TITLE
Branches is missing from Packagist

### ISSUE THREAD

**Issue by crynobone** [composer/packagist#707]
I have a <https://github.com/orchestral/database> packages which is a subsplit of <https://github.com/orchestral/kernel>. The subsplit process is working fine, however I just recently notice that the branches is missing from Packagist <https://packagist.org/packages/orchestra/database>.

![screen shot 2016-07-28 at 8 00 24 am](https://cloud.githubusercontent.com/assets/172966/17196739/5e4054dc-5499-11e6-84ab-891e7ce6f91b.png)

This doesn't happen on other subsplit of `orchestra/kernel` such as <https://packagist.org/packages/orchestra/config>

![screen shot 2016-07-28 at 8 01 26 am](https://cloud.githubusercontent.com/assets/172966/17196769/85c7be14-5499-11e6-91f9-22493b8cf067.png)

**Comment by alcohol** [comment]
Well it's even more peculiar that they work at all in most of your cases, considering almost all of them are wrong.

_As far as I know/recall_:

You cannot have a branch-alias for `dev-master` on the `3.3` branch. As the name implies, `dev-master` can only be used on the `master` branch. On the `3.3` branch you should specify an alias for `3.3-dev` (note that a suffix is used instead of prefix, see [docs](https://getcomposer.org/doc/02-libraries.md#branches)).

Why exactly do you want to use branch-aliases on your versioned branches though?

---

The `branch-alias` stuff could definitely benefit from more and better documentation however. Because even I, who has been staring at Composer source code for quite some years now, am still a bit puzzled on how exactly it should be used and to what benefit.

**Comment by alcohol** [comment]
Maybe @Seldaek can offer a bit of an explanation and perhaps even figure out a way to have packagist pick up the "missing branches".

**Comment by crynobone** [comment]
@alcohol if branch-alias can't be added on other than `master` branch, why does <https://github.com/symfony/symfony/blob/2.8/composer.json#L119> works?

Even `composer/composer` use the same structure. <https://github.com/composer/composer/blob/1.1/composer.json#L63>

**Comment by alcohol** [comment]
@crynobone I did not say it cannot be added on other branches. I simply said that aliasing `dev-master` while on a branch that is not `master`, will not be picked up by Composer but simply gets ignored. That does not mean there will not be a `dev-` or `-dev` alias though. Composer generates some of those by default.

For example, if you have a branch named `1.1`, Composer will automatically alias that as `1.1-dev` (which gets treated as `1.1.x-dev` for technical reasons).

I know Composer has it too. But that is probably only because we just very recently started having version branches, and @Seldaek hasn't cleaned up the `composer.json`. It's a left-over from when the branch was created (based on master).

Unless I'm completely wrong, in which case I will let @Seldaek correct me :p

**Comment by crynobone** [comment]
Clicking on `Update` fixed this. I'll going to close this as the problem is solved, but I would love to hear some feedback from @Seldaek if possible.

Thanks

**Comment by stof** [comment]
@crynobone if clicking on update fixed it, make sure you have the github webhook configured in the subtree repo (and with the right auth credentials). Otherwise, they will be updated only by the cron (which runs once per day or something like that)

**Comment by crynobone** [comment]
@stof It's been working before and haven't touch anything for months, which is why I report this and didn't try to use the Update button. It might be an issue with the last cron.

![screen shot 2016-07-28 at 7 04 23 pm](https://cloud.githubusercontent.com/assets/172966/17210564/473bee92-54f6-11e6-9fb2-0db9a3c2f5ac.png)

**Comment by Seldaek** [comment]
Github had some downtime earlier today so that might be the reason the update failed on our end.

**Comment by alcohol** [comment]
When you get back from your holiday, I would like to get some more details about how the branch-alias config part works though :d

**Comment by Seldaek** [comment]
It's as you described above IIRC. In branch X it reads the alias for branch
X if it's there and ignores the others.
