### ISSUE TITLE
Star synchronization

### ISSUE THREAD

**Issue by theofidry** [composer/packagist#718]
While looking at some packages, I noticed that on the search page, `nelmio/alice` had 1108 stars:
<img width="1280" alt="screen shot 2016-08-24 at 15 50 03" src="https://cloud.githubusercontent.com/assets/5175937/17935412/26e7ee20-6a13-11e6-8b21-e67d107849c7.png">

However on the package page on packagist, we can see that the number of stars is 1095.
<img width="1280" alt="screen shot 2016-08-24 at 15 50 26" src="https://cloud.githubusercontent.com/assets/5175937/17935411/26e52b9a-6a13-11e6-96e1-5b9b9d2c0d4c.png">

And on GitHub, the actual number is 1098.
<img width="1279" alt="screen shot 2016-08-24 at 15 50 36" src="https://cloud.githubusercontent.com/assets/5175937/17935410/26e4b200-6a13-11e6-93ce-c3fd69968b9e.png">

It's no big deal as it's only the number of stars AFAICS, but it's still worth reporting in case the problem is actually deeper than that.

**Comment by stof** [comment]
the number on the package page is coming from the MySQL DB, which is updated each time the package metadata is updated. This means that it will be updated the next time a commit is pushed in nelmio/alice, triggering the packagist webhook (which tells me that the github repo won 3 stars since the last change).

the search page displays the number of people favoriting nelmio/alice on Packagist itself (info which does not seem to be displayed on the package page for a weird reason), which is why the number may be different. @Seldaek can you confirm this ? I'm not sure about whether the packagist favorites have a link with github stars or no.

**Comment by Seldaek** [comment]
The "stars" in the listings might include packagist favorites + github stars, but I think that's the case too on the package page, the main reason I see for it not matching is that the search index values are cached differently than the package page. Anyway minor discrepancies that don't really matter IMO but if you want to dig in further and find a mistake somewhere (might be the sum isn't done everywhere) feel free to PR.

**Comment by theofidry** [comment]
If we're sure the problem just affect the star rating, it's all good for me ;)
