### ISSUE TITLE
Package API response outdated

### ISSUE THREAD

**Issue by k42b3** [composer/packagist#720]
Hi, yesterday I have tagged a new version v0.3.0 (https://packagist.org/packages/fusio/engine) but this version is not showing up in the API response (https://packagist.org/p/fusio/engine.json). Is this maybe a caching problem?

**Comment by runz0rd** [comment]
I was unable to get new packages (created yesterday) to show up on the API or to be recognized by composer.

**Comment by ppast** [comment]
Hi, since yesterday evening, I have the same issues. Commits (tags or dev-master) do show on my Packagist account, but the API is clearly outdated. Thus, Composer thinks there is no updates.

I have checked on twitter for any feedback from packagist, but they don't mention anything. Thanks to this issue report, they may have a look and recreate the Packagist index.

**Comment by courtney-miles** [comment]
I'm also having the same with with [milesasylum/schnoop-schema](https://packagist.org/packages/milesasylum/schnoop-schema).

The package is reflecting updates on the website, but the API is supplying outdated information.

**Comment by dhm80** [comment]
Same here. Updates on website but not via API. Please fix ASAP. Composer is not usable at the moment.

**Comment by Seldaek** [comment]
See https://twitter.com/packagist/status/772034610632990720 for updates

**Comment by ppast** [comment]
Tanks ! Everything is back to normal.
