### ISSUE TITLE
packagist not detecting current version of my package

### ISSUE THREAD

**Issue by ja-heller** [composer/packagist#757]
I've published my package with the version tag using "1.1.5". [here](https://github.com/ja-heller/coini_pw-php). After this I tried to update my [packagist version](https://packagist.org/packages/jaheller/coini_pw-php) too, using their inbuilt update function. 

Github webhooks are active too. The version still doesn't update at packagist. That's why I included the version directly into my composer.json too using `"version": "1.1.5",`. After this I tried to updateb  at packagist again. Nothing happend, there's still only the dev-master version. How to fix this?

**Comment by stof** [comment]
There is no 1.1.5 tag in your repo. there is only a ``version`` tag, which is not a name matching semver.

And setting ``version`` in a composer.json in a VCS repository can only do harm:

- it is totally ignored for branches, making it useless
- it is required to matched the version inferred from the tag name for tags, otherwise it marks the tag as invalid for Composer. So it brings no value here except breaking releases.

**Comment by ja-heller** [comment]
@stof 

What should I use for tag name & message instead of? [screenshot](https://puu.sh/t9Agw/8de2b2ee7d.png)

**Comment by stof** [comment]
The tag name should be the release version. the message can be what you want. Composer does not care (Composer does not even require using annotated tags, and non-annotated git tags don't have a message)
