### ISSUE TITLE
Packagist selects a closed branch.

### ISSUE THREAD

**Issue by Balancer** [composer/packagist#778]
I have a package with Mercurial. Once upon a time there was a `dev-master` branch. This branch was later closed, and in mercurial, the `default` branch is used by default. A few days ago the packagist suddenly began to choose not the current `dev-default` branch by default, but the old, long-closed branch of the `dev-master`.

Package: https://packagist.org/packages/balancer/bors-core

Repo: https://bitbucket.org/Balancer/bors-core

**Comment by Balancer** [comment]
Do not even help the forced branching as a temporary solution. I write in dependencies:
```
"balancer/bors-core": "dev-default"
```

But the ancient branch is installed:
```
Installing balancer/bors-core (dev-master 49b1299): Cloning 49b1299f2ddb9e5454cd633c19526a8e0e8ba087
```

**Comment by Seldaek** [comment]
I don't know why exactly, but bitbucket reports this branch as being there in the API https://api.bitbucket.org/2.0/repositories/Balancer/bors-core/refs/branches - that's why we list it. And the dev-develop branch resolves to the same version as dev-master for composer, so it ignores dev-develop because dev-master has already been saved and they conflict.

**Comment by Seldaek** [comment]
It seems like the "heads" for the branches that are gone is empty, so maybe we can use that to filter those bad branches.

**Comment by Seldaek** [comment]
Alright seems resolved.
