### ISSUE TITLE
Search excludes valid results

### ISSUE THREAD

**Issue by Sarke** [composer/packagist#783]
Why are "phpoffice/phpexcel" and other relevant results not showing when searching for "excel" (but are when you search for "exce")

https://packagist.org/search/?q=exce

https://packagist.org/search/?q=excel

See below two screenshots of searches:

![exce](http://i.imgur.com/MOV6hkI.png)

![excel](http://i.imgur.com/K1cQIO5.png)

**Comment by Sarke** [comment]
Looks like the "exce" result only returns partial matches, while the "excel" result returns whole word matches.

Which makes sense, but still... Not useful in this case

**Comment by stof** [comment]
full word matches are probably getting a higher score than partial word matches in Solr. And so they are displayed first. You can change the sorting order to sort results by number of downloads rather than by matching score, and the package might then come up on first page again (I'm quite sure that `phpoffice/phpexcel` is still matched, but sorted lower than the first page)

**Comment by Seldaek** [comment]
Yeah search algo tweaking is pretty hard, and it's probably not 100% ideal, but it's what we got :) If you can help with it that's great :)
