### ISSUE TITLE
extra .git directory exists in package

### ISSUE THREAD

**Issue by cloudsthere** [composer/packagist#796]
i create a package in packagist.org related to a github repository. After install this package in a new project, this package includes a .git directory which contains the information of the related github repository.

But this .git directory does not exists in other familiar package, like guzzle/guzzle.

when i run composer remove package/package, it just fails. Because the mod of some files in .git is 111, which could not be removed by any user.

how can i get rid of it.

**Comment by Seldaek** [comment]
That's probably because it installs it from source. You can run install with --prefer-dist or setting `composer config preferred-install dist` to remember it in your project. This should force the packages even if they are installed in dev versions to install from dist (zip files) instead of source (git clone).
