### ISSUE TITLE
Composer silently not installing later package due to extension requirements

### ISSUE THREAD

**Issue by programster** [composer/packagist#801]
I have the following scenario. I built a package that wraps around the [php aws sdk](https://packagist.org/packages/aws/aws-sdk-php). A fellow developer had an issue whereby requests were blocking forever, which I realized was somehow down to the fact that he did not have the xml extension installed, so I decided to add this to the requirements of my package by editing the composer.json file as shown below:

```
   "require": {
        "php": ">=5.6.0",
        "aws/aws-sdk-php" : "3.24.*",
        "ext-libxml" : "*",
        "ext-simplexml" : "*"
    },
```
I then bumped up the semantic version of the package from 2.0.4 to 2.0.5 and thought everything would be fine because we should automatically get minor increments because we use composer.json files like so:

```
"my-org/my-package": "2.0.*",
```

If I had bumped it to 2.1.0 then I would expect people to manually update their composer files etc.

Unfortunately, this did not result in what I expected. I had thought composer would automatically try to install or update to version 2.0.5 and if they didn't have the correct extension, they would get an error message, or at least install 2.04 and get a warning that they weren't installing the latest version of the package because of the requirements. Instead for the devs that didn't have the xml extension composer just installed 2.0.4 with no message so they had no clue that something was wrong.

**Question:** Is this the desired behavior, not getting the latest version of the package because you didn't meet the requirements and *not* being notified of this in any way. I think it would be better if the composer output "we are installing an older version of the package because your environment doesn't meet the requirements of a later version" or something similar.

I now need to to either retrospectively update the previous package releases to specify this requirement.

**Comment by Seldaek** [comment]
That is the desired behavior. It's what allows everything to work together in very complex dependency graphs where not everything can be satisfied at once using latest versions.

If you are confused why you don't get a new version installed you can always use `composer why-not org/package:2.0.5` for example which should hopefully indicate what the problem is.

**Comment by programster** [comment]
I'm not confused as to why I didn't get the latest version of the package. I just think its odd/wierd that _no info message is output_. The user incorrectly assume they are running latest when they aren't.

**Comment by Seldaek** [comment]
Yeah the problem is there are many cases where it's completely normal and expected and if composer warned it would be a nuisance.

For example composer is stuck on symfony 2.x components due to our platform config requiring php 5.3, but our requirements allow symfony 3.x to be installed. It would bother me if it nagged every time saying it can't update to symfony3.x because of x. Besides it would also be pretty hard to implement I think to have meaningful warnings as there are so many possibilities when looking at the dependency graph.

**Comment by programster** [comment]
No worries. Thanks for taking the time to review and reply to this thread.

**Comment by stof** [comment]
Note that this is exactly why composer has the `outdated` command (to see what is not using the latest version) and the `why-not` command (to understand why it is not using it)
