### ISSUE TITLE
Dependency on Algolia

### ISSUE THREAD

**Issue by falnyr** [composer/packagist#826]
Hey there,
Packagist recently switched to _Algolia_ instead of using _Solr_. Although this change was a great decision for packagist.org instance, self-hosted instances may suffer greatly since _Algolia_ is free for open-source projects only.

I know there is a possibility to use Packagist.com for private repositories, yet since `composer/packagist` is an opensource, should it be tied so much to a commercial service like _Algolia_?

I'd like to ask for your opinion on this, if `composer/packagist` is still considered to be a choice for private repositories when using a self-hosted instance or if everyone should switch to Packagist.com.

**Comment by stof** [comment]
Self-hosted instance of this source code have **never** been officially supported (the readme was recently updated to mention it instead of having it only in https://getcomposer.org/doc/articles/handling-private-packages-with-satis.md (where it was removed entirely as an option, in favor of private packagist)

**Comment by julienbourdeau** [comment]
Algolia also offers a free plan, with up to 10,000 entries. If you use your instance of packagist for your private packages, I believe your usage will fit in the free plan. :)

**Comment by falnyr** [comment]
@stof So would you instead encourage the community to start a different (new) package or improve Satis to be a viable competition to Packagist.com? You see, the current solution doesn't really work well for us and we'd like to continue using Packagist-like repository manager.

**Comment by Seldaek** [comment]
This repo was never meant to be a solution for private hosting, so I'm gonna have to mark this as won't fix.

**Comment by prhost** [comment]
unfortunately it seems to be a market strategy to force the use of Algolia, even though it has a free plan for open source, well probable that they are having an expense with Algolia, because the free plan has a limitation of 10K Records/100K Operations, my packagist already surpassed this, the way will be to use old versions of the packagist when it had the Solr, or to pay for Algolia 😢
