### ISSUE TITLE
Restore GitLab-specific documentation (and functionality as needed)

### ISSUE THREAD

**Issue by mlncn** [composer/packagist#948]
Writing as someone who has been maintaining a GitLab-hosted project on Packagist.org for more than a year, and only now (in rebellion against the "you must log in through GitHub" hook deprecation message) have i learned that i don't (currently) have to synchronize to GitHub to get updates on Packagist.org (and that Packagist's documentation once made this clear with commit 7050279ea7abfafd1) ...

* Could we have clarification if this deprecation and change coming in 2019 means that non-GitHub is no longer supported?
* Can we have documentation explicitly listing GitLab as supported and on using GitLab's support for Packagist?  See https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/14493

**Comment by Seldaek** [comment]
- The deprecation is actually GitHub deprecating things, not us. We're merely responding, and this does not affect users publishing through platforms other than GitHub. See https://developer.github.com/v3/guides/replacing-github-services/#deprecation-timeline

- Fixed in the linked commit above, thanks I wasn't aware there was a GitLab integration these days.
